### PR TITLE
First cli script

### PR DESCRIPTION
**Pull request by mothsART**

### CODE REVIEW

**Comment by lusum** [comment]
Sorry to be late, i will try and i will commit your patch,

**Comment by lusum** [comment]
please change the error messages from french to english, english is the base language for translations in this project

It also would be needed an explication like a switch --help to explain how this script works, maybe with an option to set the language and not only french without modify the config file

**Comment by mothsART** [comment]
You're absolutely right.
To achieve my goals, I preferred to split into several files.
Is very hard for me too keep a big monolithique file, surely because I would like to add some unit tests in a next iteration.

So, i added :

1. gitignore entry
2. errors messages in english
3. --help and --version options
4. forcing a language selection without update config file
5. some PEP8 migration : variables in UPPERCASE or camelCase are very ugly in python.
migrate on snake_case
6. factorisation

**Comment by lusum** [comment]
Ok, i commit this patch , but i will fix some minor problems

**Pull request merged**
