### PR TITLE
config dialog and new property

### PR DESCRIPTION
**Pull request by mothsART**
I propose a new dialog who edit config file and a new property who displaying notification or not.

### CODE REVIEW

**Comment by lusum** [comment]
I try it before merge it.

**Comment by lusum** [comment]
The commit give me an error: 

  File "./gSpeech.py", line 677, in <module>
    config = Config(CONFIGFILE)
  File "./gSpeech.py", line 595, in __init__
    'shownotification'
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'shownotification' in section: 'CONFIGURATION'

maybe you have added a section in gspeech.conf and you haven't added it in the pull request?

**Comment by mothsART** [comment]
Right : i forgot testing with an empty section on gspeech.conf => resolved.

**Comment by lusum** [comment]
Can you add a section in gspeech.conf? Like Useappindicator = True. It shuld be better to distribute a complete gspeech.conf

**Comment by lusum** [comment]
Different line numbers, but same error:

Traceback (most recent call last):
  File "./gSpeech.py", line 678, in <module>
    config = Config(CONFIGFILE)
  File "./gSpeech.py", line 596, in __init__
    'shownotification'
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'shownotification' in section: 'CONFIGURATION'

**Comment by mothsART** [comment]
@lusum : I add a property, not a section.
Same strack trace but different error : i change "has_section" by "has_option" : https://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser.has_option : check existence of section and property.

**Comment by lusum** [comment]
It works so i commit it

**Comment by mothsART** [comment]
thanks

**Pull request merged**
